--------------------------------------------------------
-- Archivo creado  - domingo-abril-21-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REC_EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REC_EMPLEADOS" 
   (	"COD_EMP" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"F_INGRESO" DATE, 
	"PUESTO" VARCHAR2(20 BYTE), 
	"EDAD" NUMBER(2,0), 
	"N_HIJOS" NUMBER(*,0), 
	"SUELDO_BASE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REC_VEHICULOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REC_VEHICULOS" 
   (	"MATRICULA" VARCHAR2(7 BYTE), 
	"KMS_ACUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REC_VIAJES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REC_VIAJES" 
   (	"COD_EMP_1" NUMBER(3,0), 
	"MATRICULA" VARCHAR2(7 BYTE), 
	"MES" NUMBER, 
	"KMS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.REC_EMPLEADOS
SET DEFINE OFF;
Insert into SYSTEM.REC_EMPLEADOS (COD_EMP,NOMBRE,F_INGRESO,PUESTO,EDAD,N_HIJOS,SUELDO_BASE) values ('1','1ªempleado',to_date('10/10/10','DD/MM/RR'),'conductor','28','0','1000');
Insert into SYSTEM.REC_EMPLEADOS (COD_EMP,NOMBRE,F_INGRESO,PUESTO,EDAD,N_HIJOS,SUELDO_BASE) values ('2','2ªempleado',to_date('01/01/11','DD/MM/RR'),'conductor','45','2','1100');
Insert into SYSTEM.REC_EMPLEADOS (COD_EMP,NOMBRE,F_INGRESO,PUESTO,EDAD,N_HIJOS,SUELDO_BASE) values ('3','3ªempleado',to_date('20/02/05','DD/MM/RR'),'director','53','3','1300');
REM INSERTING into SYSTEM.REC_VEHICULOS
SET DEFINE OFF;
Insert into SYSTEM.REC_VEHICULOS (MATRICULA,KMS_ACUM) values ('2586png','10000');
Insert into SYSTEM.REC_VEHICULOS (MATRICULA,KMS_ACUM) values ('5113ycb','105000');
Insert into SYSTEM.REC_VEHICULOS (MATRICULA,KMS_ACUM) values ('7884tbc','50000');
REM INSERTING into SYSTEM.REC_VIAJES
SET DEFINE OFF;
Insert into SYSTEM.REC_VIAJES (COD_EMP_1,MATRICULA,MES,KMS) values ('1','2586png','5','3000');
Insert into SYSTEM.REC_VIAJES (COD_EMP_1,MATRICULA,MES,KMS) values ('2','7884tbc','5','2000');
Insert into SYSTEM.REC_VIAJES (COD_EMP_1,MATRICULA,MES,KMS) values ('3','5113ycb','5','1000');
--------------------------------------------------------
--  DDL for Index PK_EMPLEADOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_EMPLEADOS" ON "SYSTEM"."REC_EMPLEADOS" ("COD_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_VEHICULOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_VEHICULOS" ON "SYSTEM"."REC_VEHICULOS" ("MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REC_EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REC_EMPLEADOS" MODIFY ("COD_EMP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REC_EMPLEADOS" ADD CONSTRAINT "PK_EMPLEADOS" PRIMARY KEY ("COD_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REC_VEHICULOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REC_VEHICULOS" MODIFY ("MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REC_VEHICULOS" ADD CONSTRAINT "PK_VEHICULOS" PRIMARY KEY ("MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REC_VIAJES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REC_VIAJES" MODIFY ("COD_EMP_1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REC_VIAJES" MODIFY ("MATRICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REC_VIAJES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REC_VIAJES" ADD CONSTRAINT "FK_EMP1" FOREIGN KEY ("COD_EMP_1")
	  REFERENCES "SYSTEM"."REC_EMPLEADOS" ("COD_EMP") ENABLE;
  ALTER TABLE "SYSTEM"."REC_VIAJES" ADD CONSTRAINT "FK_MATRI1" FOREIGN KEY ("MATRICULA")
	  REFERENCES "SYSTEM"."REC_VEHICULOS" ("MATRICULA") ENABLE;
